version: "3.7"

services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile # 빌드 파일
    image: bbonkr/example.entityframework.tree:latest # 도커 이미지 명칭
    container_name: Example.EntityFramework.Tree # 컨테이너 명칭
    restart: always
    ports:
      - 80:5000
    environment:
      - TZ=Asia/Seoul
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=<database connection string here>
      - Tree__MaxLevel=3
      - Tree__TopLevelItemsCount=5
    network_mode: bridge
    # networks:
    #   - app-network
# networks:
#   app-network:
#     external:
#       name: app-network